Algoritmo "escolha"

Var
  d :inteiro
Inicio
   escreval("     Criança esperança     ")
   escreval(" ")
   escreval(" {3}doação de 25 reais")
   escreval(" {2}doação de 30 reais")
   escreval(" {1}doação de 50 reais")
   escreval("Qual o valor da sua doação")
   leia (d)
   escolha (d)
   caso 1
      d <- 25
   caso 2
      d <- 30
   caso 3
      d <-50
   fimescolha
          escreval ("Muito obrigado pela doação de", d, "reasi")


Fimalgoritmo